---
title: 'EDS 213: Assignment 2.3'
author: "Paloma Cartwright, Mia Forsline, Daniel Kerstan, Wylie Hampson"
date: "11/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, error = FALSE)
library(here)
library(metajam)
library(tidyverse)
library(janitor)
#library(googledrive)
```



```{r, error=TRUE}
# download location data for Benthic invertebrates in Oneida Lake, New York, 1956 to present

data1_url <- "https://cn.dataone.org/cn/v2/resolve/cbfs.27.9"
path <- here("data")
download_d1_data(data1_url, path, dir_name = "Oneida_Lake_Locations")
```

```{r, error=TRUE}
# download oneida benthos 1956 to present.csv

data3_url <- "https://cn.dataone.org/cn/v2/resolve/cbfs.140.13"
path<- here("data")
download_d1_data(data3_url, path, dir_name = "Oneida_Benthos_Sp")
```

```{r,error=TRUE}
# download zebra mussel body size and biomass biometrics 2018 (Lake Mendota, WI)

data2_url <- "https://cn.dataone.org/cn/v2/resolve/https%3A%2F%2Fpasta.lternet.edu%2Fpackage%2Fdata%2Feml%2Fknb-lter-ntl%2F395%2F1%2F2fa4c5e6a54b0a5d9f22b3c92c1c3305"
download_d1_data(data2_url, path, dir_name = "Zebra_mussel_biometrics")
```
```{r, error=TRUE}
data4_url <- "https://cn.dataone.org/cn/v2/resolve/https%3A%2F%2Fpasta.lternet.edu%2Fpackage%2Fdata%2Feml%2Fknb-lter-ntl%2F394%2F1%2F2952d4a7dff04b2785604fc6b3344f3b"
path <- here("data")
download_d1_data(data4_url, path, dir_name = "NonZebra_Mendota")
```

```{r, error=TRUE}
data5_url <- "https://cn.dataone.org/cn/v2/resolve/https%3A%2F%2Fpasta.lternet.edu%2Fpackage%2Fdata%2Feml%2Fknb-lter-ntl%2F393%2F1%2F0c5ab353b07b41253740ab3126350892"

path <- here("data")
download_d1_data(data5_url, path, dir_name = "Zebra_Mendota")
```

```{r, error=TRUE}
data6_url <- "https://cn.dataone.org/cn/v2/resolve/https%3A%2F%2Fpasta.lternet.edu%2Fpackage%2Fdata%2Feml%2Fknb-lter-ntl%2F129%2F27%2Fcba9ed12834b8f315d6b10675bb60c5a"
path <- here("data")

download_d1_data(data6_url, path, dir_name = "Mendota_Water")
```


```{r}

benthos_locations <- read_d1_files(here("data", "Oneida_Lake_locations"))

benthos_data <- read_d1_files(here("data", "Oneida_Benthos_Sp"))

biometrics_data <- read_d1_files(here("data", "Zebra_mussel_biometrics"))

non_zebra_data <- read_d1_files(here("data", "NonZebra_Mendota"))

zebra_mendota_data <- read_d1_files(here("data", "Zebra_Mendota"))

mendota_water_data <- read_d1_files(here("data", "Mendota_Water"))

```


```{r}
locations <- read_csv("data/Oneida_lake_locations/Benthos_locations.csv") %>% 
  separate(col = "Longitude", 
           into = c("Longitude", "DepthGroup", "Depth", "SiteNotes", "UsageNotes"), 
           sep = ",")

locations[locations == '-999'] <- NA
```

```{r}
species <- read_csv("data/Oneida_Benthos_Sp/Oneida Benthos 1956 to present.csv") %>% 
  clean_names() %>% 
  separate(col = "zebra_mussels", into = c("zebra_mussles", "dreissena"), sep = ",")

species[species == '-999'] <- NA
species[species == '-999.0'] <- NA
  
```

```{r}
biometrics <- read_csv("data/zebra_mussel_biometrics/zebramusselbiometrics_EDI.csv") %>% 
  clean_names()

```

```{r}
zoobenthos <- read_csv("data/NonZebra_Mendota/zoobenthos_EDI.csv") %>% 
  clean_names() %>% 
  mutate(year = as.Date(as.character(year), format = "%Y")) %>% 
  mutate(year = lubridate::year(year)) %>% 
  select(year, depth, transect, replicate, number, biomass, species_level, phylum_order, area)
  
```
```{r}
zebra_mendota <- read_csv("data/Zebra_Mendota/zebramusseldensity_EDI.csv") %>% 
  clean_names() %>% 
  mutate(year = lubridate::year(date)) %>% 
  select(transect, depth, replicate, totalsample_count, area, density_m2, year)
```

```{r}
mendota_water <- read_csv("data/Mendota_Water/ntl129_1_v5.csv") %>% 
  clean_names() %>% 
  filter(year4 >= 2016,  year4 <= 2018) %>%
  rename(year = year4) %>% 
  select(year, sampledate, avg_air_temp, avg_chlor, avg_do_raw) %>% 
  group_by(year) %>% 
  summarize(yearly_temp_avg = mean(avg_air_temp, na.rm = TRUE))
  
```

```{r}
mid_data <- full_join(zoobenthos, zebra_mendota, 
                      by = c("year", "transect", "depth", "area", "replicate")) 

complete_data <- full_join(mid_data, mendota_water, by = "year")

```



